services:
  - type: web
    name: fastapi-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  - type: static
    name: react-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
